<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About us</title>
    <link rel="stylesheet" href="static/stylesheet.css">
</head>
<body>
<div>
    <a href="index">Home</a>
    <a href="about">About Us</a>
</div>

</body>
</html>